name: Deploy Images to Dockerhub

on:
  push:
    tags:
  workflow_dispatch:

jobs:
  build-latest:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to DockerHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: 'Build cctv_recording Image'
        run: |
          docker build . --tag docker.io/tafeen/cctv_recording:${{github.ref_name}}
          docker push docker.io/tafeen/cctv_recording:${{github.ref_name}}

  build-version:
    runs-on: ubuntu-latest
    if: github.ref_type == 'refs/heads/master'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to DockerHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: 'Build cctv_recording Image'
        run: |
          docker build . --tag docker.io/tafeen/cctv_recording:latest
          docker push docker.io/tafeen/cctv_recording:latest
